channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pytorch=1.13.*=*cuda* # Need to specifically request cuda version
  - torchvision=0.14.*
  - ipykernel=6.29.*
  - mkl<=2024.0 # Need to downgrade mkl for compatibility with pytorch
  - pip>=23
  # Install pip requirements with `pip install -r requirements.txt`
