data_dir: ${oc.env:DATASET_DIR}/EvalDatasets/lfw
output_dir: results
file_ext: .jpg
data_name: lfw
model_name: magface-r50
ckpt_fp: checkpoints/magface/magface_iresnet50_MS1MV2_ddp_fp32.pth
backbone: iresnet50
save_config: false
