seed: 42
results_dir: ${oc.env:EXPERIMENT_DIR}/femb
method_name: femb_arcface_ms1mv2
datamodule:
  class_path: src.datamodule_mxnet.MXFaceDatamodule
  init_args:
    root_dir: ${oc.env:DATASET_DIR}/TrainDatasets/ms1mv2
    batch_size: 128
    num_workers: 8
pl_module:
  class_path: src.pl_module.FembModule
  init_args:
    backbone: iresnet100
    embed_dim: 512
    pretrained_bb: false
    header: arcface
    n_classes: 85742
    lr: 0.02
    weight_decay: 0.0005
trainer:
  class_path: Trainer
  init_args:
    accelerator: gpu
    devices:
      - 0
      - 1
      - 2
      - 3
    strategy: ddp
    precision: 16
    num_sanity_val_steps: 0
    max_epochs: 5
    log_every_n_steps: 50
pbar_refresh_rate: 10
